[package]
name = "gather_files"
version = "0.2.4"
edition = "2021"
description = "Gather project files for LLM processing"
authors = ["herring101"]
license = "MIT"
repository = "https://github.com/herring101/gather_files"
readme = "README.md"
keywords = ["llm", "files", "gather", "development"]
categories = ["development-tools", "command-line-utilities"]

[dependencies]
chrono = "0.4.39"
walkdir = "2.5.0"
globset = "0.4.15"
clap = "4.5.23"

[dev-dependencies]
tempfile = "3.14.0"