name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.check_release.outputs.release_exists == 'true' && steps.check_release.outputs.upload_url || steps.create_release.outputs.upload_url }}
      version: ${{ steps.get_version.outputs.version }}
    steps:
      - name: Get version from tag
        id: get_version
        run: echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Check if release exists
        id: check_release
        run: |
          RELEASE_ID=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/releases/tags/${{ github.ref_name }}" | \
            jq -r '.id // ""')
          
          if [ -n "$RELEASE_ID" ] && [ "$RELEASE_ID" != "null" ]; then
            echo "Release already exists for tag ${{ github.ref_name }}"
            echo "release_exists=true" >> $GITHUB_OUTPUT
            echo "release_id=$RELEASE_ID" >> $GITHUB_OUTPUT
            # Get upload URL for existing release
            UPLOAD_URL=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              "https://api.github.com/repos/${{ github.repository }}/releases/$RELEASE_ID" | \
              jq -r '.upload_url')
            echo "upload_url=$UPLOAD_URL" >> $GITHUB_OUTPUT
          else
            echo "No release exists for tag ${{ github.ref_name }}"
            echo "release_exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Create Release
        id: create_release
        if: steps.check_release.outputs.release_exists != 'true'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

  build:
    needs: create-release
    # Run even if the create-release job skipped creating a new release
    if: always()
    name: Build and Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact_name: gather_files
            asset_name: gather_files-linux-amd64
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            artifact_name: gather_files
            asset_name: gather_files-linux-musl-amd64
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact_name: gather_files.exe
            asset_name: gather_files-windows-amd64.exe
          - os: macos-latest
            target: x86_64-apple-darwin
            artifact_name: gather_files
            asset_name: gather_files-macos-amd64
          - os: macos-latest
            target: aarch64-apple-darwin
            artifact_name: gather_files
            asset_name: gather_files-macos-arm64
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            artifact_name: gather_files
            asset_name: gather_files-linux-arm64

    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
      
      - name: Install musl-tools (Linux musl only)
        if: matrix.target == 'x86_64-unknown-linux-musl'
        run: |
          sudo apt-get update
          sudo apt-get install -y musl-tools
      
      - name: Install cross-compilation tools (ARM Linux only)
        if: matrix.target == 'aarch64-unknown-linux-gnu'
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
      
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target ${{ matrix.target }}
        env:
          CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER: aarch64-linux-gnu-gcc
      
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: target/${{ matrix.target }}/release/${{ matrix.artifact_name }}
          asset_name: ${{ matrix.asset_name }}
          asset_content_type: application/octet-stream

  create-installers:
    needs: create-release
    # Run even if the create-release job skipped creating a new release
    if: always()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Generate install scripts
        run: |
          # PowerShellスクリプトの生成
          cat > install.ps1 << 'EOF'
          $ErrorActionPreference = 'Stop'
          
          $repo = "herring101/gather_files"
          $file = "gather_files-windows-amd64.exe"
          $releases = "https://api.github.com/repos/$repo/releases"
          
          Write-Output "Fetching latest release..."
          $tag = (Invoke-WebRequest $releases | ConvertFrom-Json)[0].tag_name
          
          $download = "https://github.com/$repo/releases/download/$tag/$file"
          $installDir = "$env:LocalAppData\Programs\gather_files"
          $output = "$installDir\gather_files.exe"
          
          if (-not (Test-Path $installDir)) {
              New-Item -ItemType Directory -Path $installDir -Force | Out-Null
          }
          
          Write-Output "Downloading $download..."
          Invoke-WebRequest $download -Out $output
          
          Write-Output "Installing to $output"
          
          $currentPath = [Environment]::GetEnvironmentVariable("Path", "Machine")
          if (-not $currentPath.Contains($installDir)) {
              Write-Output "Adding installation directory to system PATH..."
              [Environment]::SetEnvironmentVariable(
                  "Path",
                  "$currentPath;$installDir",
                  "Machine"
              )
              $env:Path = "$env:Path;$installDir"
              Write-Output "PATH has been updated successfully."
          }
          
          Write-Output "Installation completed!"
          Write-Output "You can now run 'gather_files' from your terminal."
          EOF
          
          # シェルスクリプトの生成
          cat > install.sh << 'EOF'
          #!/bin/sh
          
          REPO="herring101/gather_files"
          RELEASES_URL="https://api.github.com/repos/$REPO/releases"
          
          case "$(uname -sm)" in
              "Darwin x86_64")
                  PLATFORM="macos"
                  ARCH="amd64"
                  FILE="gather_files-macos-amd64"
                  ;;
              "Darwin arm64")
                  PLATFORM="macos"
                  ARCH="arm64"
                  FILE="gather_files-macos-arm64"
                  ;;
              "Linux x86_64")
                  PLATFORM="linux"
                  ARCH="amd64"
                  FILE="gather_files-linux-musl-amd64"
                  ;;
              "Linux aarch64")
                  PLATFORM="linux"
                  ARCH="arm64"
                  FILE="gather_files-linux-arm64"
                  ;;
              *)
                  echo "Unsupported platform: $(uname -sm)"
                  exit 1
                  ;;
          esac
          
          echo "Detected platform: $PLATFORM-$ARCH"
          
          if ! TAG=$(curl -fsSL $RELEASES_URL | grep -o '"tag_name": "[^"]*' | head -n 1 | cut -d'"' -f4); then
              echo "Failed to fetch latest release information"
              exit 1
          fi
          
          DOWNLOAD_URL="https://github.com/$REPO/releases/download/$TAG/$FILE"
          INSTALL_DIR="$HOME/.local/bin"
          
          mkdir -p "$INSTALL_DIR"
          
          echo "Downloading gather_files..."
          if curl -fsSL "$DOWNLOAD_URL" -o "$INSTALL_DIR/gather_files"; then
              chmod +x "$INSTALL_DIR/gather_files"
              
              if ! echo "$PATH" | grep -q "$INSTALL_DIR"; then
                  SHELL_CONFIG=""
                  if [ -f "$HOME/.zshrc" ]; then
                      SHELL_CONFIG="$HOME/.zshrc"
                  elif [ -f "$HOME/.bashrc" ]; then
                      SHELL_CONFIG="$HOME/.bashrc"
                  fi
                  
                  if [ -n "$SHELL_CONFIG" ]; then
                      echo "export PATH=\"\$PATH:$INSTALL_DIR\"" >> "$SHELL_CONFIG"
                      echo "Added $INSTALL_DIR to PATH in $SHELL_CONFIG"
                      echo "Please restart your terminal or run: source $SHELL_CONFIG"
                  else
                      echo "Please add $INSTALL_DIR to your PATH manually"
                  fi
              fi
              
              echo "Installation completed!"
              echo "You can now run 'gather_files' from your terminal."
          else
              echo "Download failed"
              exit 1
          fi
          EOF
          
          chmod +x install.sh
      
      - name: Upload Install Scripts
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: install.ps1
          asset_name: install.ps1
          asset_content_type: text/plain
      
      - name: Upload Install Script (Shell)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: install.sh
          asset_name: install.sh
          asset_content_type: text/plain